apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
  namespace: esg-demo-platform-own
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/redis
  storageClassName: standard
