apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv
  namespace: esg-demo-platform-own
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/postgresql
  storageClassName: standard
