apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: headers
spec:
  headers:
    customRequestHeaders:
      X-CSRFToken: "your-csrf-token-value"
    customResponseHeaders:
      Set-Cookie: "CSRF-TOKEN=your-csrf-token-value; Path=/; Secure; HttpOnly"